# =====================================================
# OCR_Compare 系統設定檔
# 根據 frmSetup.cs 產生
# =====================================================

# MySQL 資料庫設定
mysql:
  host: localhost
  port: 3306
  database: ocr_compare
  user: root
  password: Gwgplus24294096
  charset: utf8mb4
  connect_timeout: 10
  pool_size: 5
  pool_timeout: 30

# UI 介面設定
ui:
  language: zh_TW
  theme: default
  font_size: normal
  full_screen: false
  auto_logout: 300
  table_rows_per_page: 10

  
# 路徑設定
paths:
  # OCR 圖片來源路徑
  ocr_image_save_path: "E:\\OCR_Images\\Source"
  
  # 資料庫圖片儲存路徑
  db_image_save_path: "E:\\OCR_Images\\Database"
  
  # 匯出預設路徑
  export_default_path: "E:\\OCR_Export"
  
  # OCR 備份路徑
  ocr_backup_path: "E:\\OCR_Backup"

# PV200 設備設定
cognex:
  # Cognex IP 位址
  #ip: "192.168.1.100"
  ip: "127.0.0.1"
  # Cognex 通訊埠
  port: 23
  
  # Cognex 命令埠 (已註解，保留供未來使用)
  # port_cmd: 503

# 影像處理設定
image_processing:
  # 偏移量 X
  offset_x: 100
  
  # 偏移量 Y
  offset_y: 100
  
  # 放大比例 (0.1 - 3.0)
  scale: 0.7

# 時間設定
timing:
  # OCR 重試次數
  ocr_retry_time: 3
  
  # 圖片檢查等待時間 (毫秒，最小 1000)
  pic_wait_time: 2000

# 系統設定
system:
  # 是否啟用除錯模式
  debug_mode: false
  
  # 日誌等級 (DEBUG, INFO, WARN, ERROR)
  log_level: "INFO"
  
  # 日誌檔案路徑
  log_file_path: "C:\\OCR_Logs\\ocr_compare.log"

# 安全設定
security:
  # 是否啟用密碼驗證
  enable_password_validation: true
  
  # 密碼最小長度
  min_password_length: 6
  
  # 密碼複雜度要求
  password_complexity:
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: false

# 備份設定
backup:
  # 是否啟用自動備份
  enable_auto_backup: true
  
  # 備份頻率 (小時)
  backup_interval_hours: 24
  
  # 保留備份天數
  backup_retention_days: 30

# 匯出設定
export:
  # 預設匯出格式 (CSV, EXCEL, JSON)
  default_format: "EXCEL"
  
  # 是否包含圖片路徑
  include_image_path: true
  
  # 是否包含時間戳記
  include_timestamp: true

# 通知設定
notifications:
  # 是否啟用錯誤通知
  enable_error_notifications: true
  
  # 是否啟用成功通知
  enable_success_notifications: false
  
  # 通知方式 (EMAIL, SMS, NONE)
  notification_method: "NONE"
  
  # 電子郵件設定 (如果使用 EMAIL 通知)
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    from_address: ""
    to_addresses: []

# 效能設定
performance:
  # 最大並行處理數
  max_concurrent_processes: 4
  
  # 記憶體使用限制 (MB)
  memory_limit_mb: 1024
  
  # 圖片快取大小 (MB)
  image_cache_size_mb: 100

# 開發者設定 (僅供開發使用)
development:
  # 是否啟用詳細日誌
  verbose_logging: false
  
  # 是否啟用效能監控
  enable_performance_monitoring: false
  
  # 測試模式
  test_mode: false
